name: ${pom.name}
main: hef.IRCTransport.IRCTransport
version: ${pom.version}
website: ${pom.url}
author: hef
database: true
description: >
             IRC Transport Plugin for minecraft chat.
             Forwards all chat messages from minecraft to irc,
             and all irc messages to minecraft players.
commands:
  join:
    description: Join an IRC channel
    usage: |
           /<command> <channel>
           Example: /<command> #minecraft
  leave:
    description: Leave an IRC channel.
    usage: |
           /<command> <channel> [message]
           Example: /<command> #warez
           Example: /<command> #porn see you guys tomorrow
  channel:
    description: Switch active channel
    usage: |
           /<command> <channel>
           Example: /<command> #minecraft
           Example: /<command> #acm
  msg:
    description: Send a private message
    usage: |
           /<command> <player> [message]
           Example: /<command> pbrhef Awesome thing you built! 
  nick:
    description: Change your display name.
    usage: |
           /<command> <name>
           Example: /<command> Sam
  names:
    description: get a list of channel members
    usage: |
           /<command> [channel]
           /<command>
           /<command> #minecraft
  me:
    description: perform an action
    usage: |
           /<command> <action>
           /<command> dances with the devil in the pale moonlight.
  topic:
    description: get and set the channel topic
    usage: |
           /<command> [topic]
           /<command>
           /<command> Our hearts are extended to the 17 victims of the recent internet fraud
  whois:
    description: Gets information about a nick
    usage: |
           /<command> [nick]
           /<command> Sam
  irc_listbots:
    description: List bots
    usage: |
           /<command>
